### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by ocornut** [Extrawurst/cimgui#1]
That's very interesting. I was looking at it just earlier. I think it'd be quite hard to do a satisfying C-wrapper. ImGui relies on default parameters and overloaded functions quite a lot.

How come your cimgui.h has default parameters? Would that compile with raw C ?

At first glance I would suggest
ig_BeginChild2 -> ig_BeginChildEx
ig_SetWindowPos2 -> SetWindowPosByName
ig_PushID(const char* str_id) -> PushIdStr
ig_PushID2(const void* ptr_id) -> PushIdPtr
ig_PushID3(const int int_id) ->PushIdInt
ig_RadioButton -> RadioButtonBool
ig_RadioButton2-> RadioButton

ig_TreeNode(const char* str_label_id); --> TreeNode
ig_TreeNode2(const char* str_id, const char* fmt, ...); -> TreeNodeStr
ig_TreeNode3(const void* ptr_id, const char* fmt, ...); -> TreeNodePtr
ig_TreeNodeV(const char* str_id, const char* fmt, va_list args); --> TreeNodeStrV
ig_TreeNodeV2(const void* ptr_id, const char* fmt, va_list args); --> TreeNodePtrV
ig_TreePush(const char* str_id = NULL); -> TreePushStr
ig_TreePush2(const void* ptr_id = NULL); -> TreePushPtr

Not sure about those yet
ig_Selectable(const char* label, bool selected = false, const ImVec2 size = ImVec2(0, 0)); --> ig_Selectable2(const char* label, bool* p_selected, const ImVec2 size = ImVec2(0, 0)); --> 

ig_ListBox(const char* label, int* current_item, const char** items, int items_count, int ig_ListBox2(const char* label, int* current_item, bool(*items_getter)(void* data, int idx, const char** out_text), void* data, int items_count, int height_in_items = -1);

ig_Value(const char* prefix, bool b); --> ValueBool, 
ig_Value2(const char* prefix, int v); --> ValueInt
ig_Value3(const char* prefix, unsigned int v); --> ValueUint
ig_Value4(const char* prefix, float v, const char* float_format = NULL);-> ValueFloat
etc.

It's a tough nut to crack well.

**Comment by Extrawurst** [comment]
Yeah I was not satisfied with the naming either. i am happy to incorporate those changes since it makes it more clear what the methods are doing differently. to bad c does not support overlaoding. 

as a raw c file this does not compile, no (not yet). but my intention was to first get the bulk of it working so i can use in my actual project (using D - which supports the C ABI) and my first move was to create the C-like wrapper and copy all methods to D to be able to keep the defaults there. i will remove those in here later.

**Comment by ocornut** [comment]
Not sure about the ig_ prefix either, but then the problem with ImGui_ is that it is such an overused word (the problem of naming is still in the air https://github.com/ocornut/imgui/issues/21 )

**Comment by ocornut** [comment]
I suppose ImGui_* prefix would feel more like an official sanctioned version.
Then again my worry is that I'm not sure we can get the same amount of comfort in a language without default parameters and I wouldn't have designed ImGui API the same way for such language. So I worry slightly that C/C++ people may use a C API "by default" and not take advantage of the "better" original.

So maybe it's good to use another prefix at the moment before you see if it can reach a desired quality. Does those thoughts make sense?

**Comment by Extrawurst** [comment]
yeah at first i thought `cimgui_` but in the end i settled for less verbose. but i am open to any better ideas

**Comment by Extrawurst** [comment]
i guess in most cases the c-api is just an intermediate layer to be able to use imgui from all sorts of programming languages. I will make the readme stating more clear that this is the main purpose and that for C++ guys the original is the way to go. oh dear i wouldn't wanna use it in pure C without default params^^

**Comment by Extrawurst** [comment]
ok the readme is clearer now, i hope.

**Comment by Extrawurst** [comment]
finished the renamings
