### ISSUE TITLE
trying to use bindings in Golang

### ISSUE THREAD

**Issue by michelson** [Extrawurst/cimgui#12]
Hi, I would like to interface Imgui with Golang through this library , but I don't know where to start with cimgui.
I had already compiled the library with, make command, to a dynamic library and also to a shared library. the problem is I getting some errors when I try to build the go program and also when try to compile the test.c file.

this is what I've tried so far:

```go
/*
#cgo CFLAGS: -I./cimgui
#cgo LDFLAGS: -L. -lcimgui
#include <cimgui.h>
*/
import "C"

func main() {

	fmt.printLn("Hello world")
}
```

also I've tried to include the header directly , like

```go
/*
#include "cimgui/cimgui.h"
*/
```

and also I've tried to compile the test.c with `gcc -c test.c`
In all the cases I get the same error.

you can see the output of the error here: https://gist.github.com/michelson/8ee0996d819bb0ff8167d76d964b0fc4

thanks in advance and thanks for this library

best

**Comment by michelson** [comment]
I've tried the SWIG library to build a go wrapper , but it seems that the same error is raised.

cimgui.swig file

```
%module cimgui

/* Let's just grab the original header file here */
%include "cimgui.h"
```

then run the swig `swig -go -cgo -intgosize 64 cimgui.swig`

and then try to build the library

`go build`

the error is very similar to the error I've pasted before:
```
./cimgui_wrap.c:228:1: error: unknown type name 'ImGuiIO'
./cimgui_wrap.c:229:3: error: use of undeclared identifier 'ImGuiIO'
./cimgui_wrap.c:229:12: error: use of undeclared identifier 'result'
./cimgui_wrap.c:230:3: error: use of undeclared identifier 'ImGuiIO'
./cimgui_wrap.c:230:12: error: use of undeclared identifier '_swig_go_result'
./cimgui_wrap.c:233:3: error: use of undeclared identifier 'result'
./cimgui_wrap.c:233:13: error: use of undeclared identifier 'ImGuiIO'
./cimgui_wrap.c:233:22: error: expected expression
./cimgui_wrap.c:234:5: error: use of undeclared identifier 'ImGuiIO'
./cimgui_wrap.c:234:15: error: expected expression
./cimgui_wrap.c:234:17: error: use of undeclared identifier '_swig_go_result'
./cimgui_wrap.c:234:36: error: use of undeclared identifier 'ImGuiIO'
./cimgui_wrap.c:234:45: error: expected expression
./cimgui_wrap.c:235:10: error: use of undeclared identifier '_swig_go_result'
./cimgui_wrap.c:239:1: error: unknown type name 'ImGuiStyle'
./cimgui_wrap.c:240:3: error: use of undeclared identifier 'ImGuiStyle'
./cimgui_wrap.c:240:15: error: use of undeclared identifier 'result'
./cimgui_wrap.c:241:3: error: use of undeclared identifier 'ImGuiStyle'
./cimgui_wrap.c:241:15: error: use of undeclared identifier '_swig_go_result'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```


any hints ? please help 🙏

**Comment by Extrawurst** [comment]
Hi @michelson sorry that u got so many problems using this lib in go, but i am no go user and neither did I ever used swig :( so i am afraid i cannot help u much here.
