### ISSUE TITLE
ImFontConfig constructor missing?

### ISSUE THREAD

**Issue by paniq** [Extrawurst/cimgui#14]
It appears that the default constructor for ImFontConfig has no C wrapper. Some of the values are not zero by default, so a simple clear of an ImFontConfig object is not enough.

**Comment by o01eg** [comment]
It was reintroduced in https://github.com/Extrawurst/cimgui/pull/37

**Comment by yosikawa** [comment]
regarding to ImFontConfig_DefaultConstructor,
Sorry this is my editorial mistake. 
Let me provide the amendment commit

**Comment by yosikawa** [comment]
now ready to pull. please review my amendments.

**Comment by Extrawurst** [comment]
fixed in https://github.com/Extrawurst/cimgui/pull/43

**Comment by Extrawurst** [comment]
Thank you @yosikawa for your effort!
