### ISSUE TITLE
VS2013 compile turn on==> error C2371: ImDrawIdx : redefine; different base types

### ISSUE THREAD

**Issue by zhouxs1023** [Extrawurst/cimgui#16]
I used vs2013 compile cimgui, but turn on error c2371 ImDrawIdx : redefine; different base types as below:
![qq 20160626221700](https://cloud.githubusercontent.com/assets/905931/16362874/5f0dfe02-3bec-11e6-82c9-99db85b1ea46.png)

pls help me to solve？

**Comment by Extrawurst** [comment]
What do you mean by "turn on error C2371"? The solution builds fine for me on VS2015 without any errors

**Comment by ShiiroSan** [comment]
Same issue here with VS2015... Just opening the visual studio project and compile doesn't seems to work, does it need any requirements?

**Comment by Extrawurst** [comment]
@ShiiroSan I just built it successfully in VS2015. Can you provide more infos what errors you are seeing ?

**Comment by ShiiroSan** [comment]
Same as the guy OP. Telling that this is already declared. But no problem with 1.48 version. Only 1.49.
