### ISSUE TITLE
Could you add an actual test/example file?

### ISSUE THREAD

**Issue by stacksmith** [Extrawurst/cimgui#20]

**Comment by dpethes** [comment]
Would it be worth it? The changes from cpp api are really easy to figure out, and you should look into sources for documentation anyway.

**Comment by Extrawurst** [comment]
i agree with @dpethes - what is kind of example are u missing @stacksmith ?

**Comment by stacksmith** [comment]
Honestly, I can't remember the exact problem; it was like 6 months ago!  While it is pretty obvious why it's a good idea to have an example that demonstrates the features of a library in order for the user to get a 'quick start', 'hit the ground running', and at least have something working when they are stumped by what is likely to be inadequate documentation (almost always the case for wrapped libraries), consider the following:

While you are a cimgui expert, I am looking for a simple UI library for a time-sensitive project.  My client is an advertising house that is very sensitive to good looking type, fonts and layout, and I have a list of possible libraries I can use and very little time before my presentation. 

Several of these (like McClim) are immediately ruled out - I looked at the demos, and they don't do sub-pixel antialiasing on type.  Great - 5 minutes and I know the answer.

Then there is cimgui.  I can either spend a day trying to figure out how to put together something, or dick around with C++ ("never again" was my promise to my grandmother).

Now you can say "why not use many of the pre-built demos floating around"?  Well, if the type looks OK, I still need to plug in the client's fonts etc.   How?  There is no 'skeleton application', or a 'bare-bones demo', etc.  So I had to rule cimgui out, even though it looked like a possible fit.

So please consider the power of being able to do `(cimgui:demo)` immediately after getting it from quicklisp as compared to a day of being frustrated reading docs for a blub language.   I understand that your position may be 'I just wrote the wrapper, go figure it out yourself, dumb-ass' -- in which case feel free to close the issue and forget about it.  But I sincerely hope that you would do your audience the favor of placing a small demo or a tutorial for a minimal example - a window with a button and some text in a box, or something like that.  It would be helpful.

Apologies for what appears to be sarcasm, but I am genuinely trying to help.

**Comment by Extrawurst** [comment]
Like most people I do this in my spare time for free you know. it is open source - if you see something missing feel free to create a pull request. Since it is just a wrapper, obviously I will not recreate Demos That will look almost exactly the same as the original c++ ones. But thanks for taking the time to give me your feedback - Appreciated
