### ISSUE TITLE
Allow disabling `__declspec(dllexport)`

### ISSUE THREAD

**Issue by Kukkimonsuta** [Extrawurst/cimgui#31]
When statically linking I'd like to remove all exported symbols to avoid collisions, therefor I propose either allowin to define `CIMGUI_API` manually or add new define `CIMGUI_NO_EXPORT` and don't include `__declspec(dllexport)` if set.

I can PR if the change is approved.

**Comment by Extrawurst** [comment]
sure you can introduce a new define to get rid of it, as long as the defaults stay the same. thanks in advance
