### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by adammaj1** [Extrawurst/cimgui#44]
Hi,

` git clone https://github.com/Extrawurst/cimgui
Cloning into 'cimgui'...
remote: Counting objects: 489, done.
remote: Total 489 (delta 0), reused 0 (delta 0), pack-reused 489
Receiving objects: 100% (489/489), 444.41 KiB | 290.00 KiB/s, done.
Resolving deltas: 100% (325/325), done.
Checking connectivity... done.

a@zelman:~$ cd cimgui

a@zelman:~/cimgui$ ls
cimgui  imgui  LICENSE  menus-api.gif  README.md  screenshot.png

a@zelman:~/cimgui$ cd cimgui

a@zelman:~/cimgui/cimgui$ ls
cimgui.cpp  cimgui.sln      cimgui.vcxproj.filters  fontAtlas.cpp    Makefile
cimgui.h    cimgui.vcxproj  drawList.cpp            listClipper.cpp  test.c

a@zelman:~/cimgui/cimgui$ make

g++ -I../../ -Wall -shared -fPIC -c -o cimgui.o cimgui.cpp
cimgui.cpp:2:28: fatal error: ../imgui/imgui.h: No such file or directory
compilation terminated.
Makefile:48: polecenia dla obiektu 'cimgui.o' nie powiodły się
make: *** [cimgui.o] Błąd 1
`
My system 
Ubuntu 16.04 LTS

**Comment by Extrawurst** [comment]
if you git clone recursivley you should also have the missing files, since they are in a git submodule:
```
git clone --recursive ....
```
see this useful git resource: https://github.com/k88hudson/git-flight-rules
