### ISSUE TITLE
ImGui 1.60

### ISSUE THREAD

**Issue by sonoro1234** [Extrawurst/cimgui#49]
Hi,

I am working on ImGui 1.60. I think it would be good to share it but in a different branch.
@Extrawurst  What do you think about it?

Best Regards
victor bombi

**Comment by Extrawurst** [comment]
Hi Victor,
thanks for your support. Since imgui 1.60 is not yet released and WIP I agree that it should not be in the normal release branch yet. I am looking forward to merge it in once it is officially released, feel free to open a PR already with the current status so that people have an easier time finding it. Once 1.60 is release I would like you to update the branch with a squashed single commit to merge it in.

Cheers,
Stephan

**Comment by sonoro1234** [comment]
Ok.
You will have to explain me how to do "a squashed single commit to merge it in" when time arrives.

**Comment by Extrawurst** [comment]
thanks!

sure, squash is basically a way to merge multiple commits into one. its a special form of rebase. see here: https://stackoverflow.com/a/5189600

and here: https://github.com/k88hudson/git-flight-rules#i-need-to-combine-commits

**Comment by Extrawurst** [comment]
never mind i just realize i can do this when merging the PR on my end! Thanks again! :)

**Comment by Extrawurst** [comment]
@ocornut thanks I know 1.60 is out. On the weekend latest I will grab this branch and adapt whatever is missing. but yeah smaller releases would make it much easier.

Actually I already use those git tags to match your releases. The only difference so far is that I never moved them to add fixes, that I could do in the future actually.

**Comment by ocornut** [comment]
> Actually I already use those git tags to match your releases. The only difference so far is that I never moved them to add fixes, that I could do in the future actually.

Oops, my apologies! I have no idea how I missed them, I think on github I often expect to see them under "branches" while they are merely one click away. Sorry!

**Comment by ocornut** [comment]
imgui doesn’t guarantee data layout / binary compatibility accross version, if bindings needs to duplicate data structures they’ll need to be updated accordingly. 

Perhaps the bindings should static assert for matching structure size and matching offset of a few selected members to make mismatched structures visible.

I can’t document every data layout change, but the update should be fairly easy to perform.

**Comment by sonoro1234** [comment]
My next experiment is going to be an automatic extraction of structs and enums from imgui.h
Would be great for the future.

**Comment by sonoro1234** [comment]
@Extrawurst It is not ready. As I told above structs are not according to 1.60 already

I am working on automatically generating enums and structs.
My first problem now is the differences between cimgui.h structs and imgui structs:

In cimgui you have
```
struct ImVec2
{
    float x, y;
};

struct Other
{
    struct ImVec2 foo;
};
```

while in imgui.h  (being C++) would be:
```
struct ImVec2
{
    float x, y;
};

struct Other
{
    ImVec2 foo;
};
```

finally my solution is:
```
struct ImVec2
{
    float x, y;
};
typedef struct ImVec2 ImVec2;
struct Other
{
    ImVec2 foo;
};
```

Do you agree with this solution for structs in cimgui.h or this would break something?

**Comment by sonoro1234** [comment]
Other question:
why
https://github.com/Extrawurst/cimgui/blob/master/cimgui/cimgui.h#L45

**Comment by sonoro1234** [comment]
Everything working here except glyphs which I am investigating

**Comment by sonoro1234** [comment]
@Extrawurst 
Everything works now.
My last commit provides a way to automatically generate imgui_structs.h which can be included in cimgui.h by defining CIMGUI_DEFINE_ENUMS_AND_STRUCTS when you need to generate your binding as I am doing in LUAJIT-imgui
This is a working base for adding (not automatically) the new function wrappers needed in 1.60

now the PR cant be merged because it was partially merged before.
Perhaps last merging should be reverted before applying the new PR?

**Comment by sonoro1234** [comment]
Now I am begining the work for function generation. The main problem happens with overloaded function names. I would like to make naming algorytmic but already used names in cimgui which other people use in its binding should be taken in account.
For more on this see https://github.com/ocornut/imgui/issues/1782

**Comment by Extrawurst** [comment]
sounds like a good idea. you could whitelist the overload names in an automated approach

**Comment by sonoro1234** [comment]
@Extrawurst  last PR merge was incomplete and master is broken:
https://github.com/Extrawurst/cimgui/issues/49#issuecomment-384357965

Now the PR cant be merged because it was partially merged before.
Perhaps last merging should be reverted before applying the new PR?
Or better revert in master and apply new PR to a new branch (master1.60 or master_auto?) until finished.
