### ISSUE TITLE
Better namespace/prefix organisation

### ISSUE THREAD

**Issue by cwkx** [Extrawurst/cimgui#5]
First of, thanks for providing & updating such a very useful wrapper!

I'm really not a fan of the "ig_" prefix conflicting with the PascalCase style of imgui; I see this was mentioned in a previous issue; there should be some more elegant way to control it such as the struct answers in: http://stackoverflow.com/questions/389827/namespaces-in-c e.g. to get rid of the underscore, giving:
ImGui.Begin(); or ig.Begin();

**Comment by Extrawurst** [comment]
yeah the pascal casing it kinda inconsistent. I will maybe go for removing the underscore like this `igBegin`. what do you think? I am not sure if a struct-to-fake-a-namespace is such a good idea when keeping in mind that this is a wrapper to simplify using imgui in other languages...

**Comment by cwkx** [comment]
I think `igBegin` is a lot nicer; similar to gl style which is nice, e.g. deprecated `glBegin`  :)

**Comment by Extrawurst** [comment]
I will change that later today. it's gonna be just find/replace. although I have no idea how many are using this lib. but it will break everyones code...
