### ISSUE TITLE
Filters are missing

### ISSUE THREAD

**Issue by ddude** [Extrawurst/cimgui#9]
Hello, I'm trying to use the ImGuiTextFilter class from your C bindings (which are great otherwise!) and couldn't find anything related to the use of text filters, especially the ```Draw``` and ```PassFilter``` methods.

**Comment by Extrawurst** [comment]
yea the filters are not yet wrapped for c yet. but it is easy to copy the code inside those methods and use it with cimgui. Filters are just for convenience. Feel free to extend cimgui with Filters via a PR

**Comment by ddude** [comment]
I'll probably have a very big PR for you in a few days, I basically already upgraded cimgui to the latest 1.46WIP and added almost every missing calls, I just need to wrap the internal API as well and I'll send it your way.

**Comment by Extrawurst** [comment]
I just updated to imgui 1.45 and tagged that (https://github.com/Extrawurst/cimgui/releases/tag/v1.45) so we are good to go to a WIP version now. please rebase your changes to go from there.

**Comment by Extrawurst** [comment]
@ddude any news here ?
